name: Trigger Country Workflow

on:
  workflow_dispatch:
    inputs:
      country:
        description: "Enter country name"
        required: true
        default: "India"

jobs:
  trigger:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Run trigger script
        env:
          GITHUB_TOKEN: ${{ secrets.WORKFLOW_TRIGGER_TOKEN }}
        run: |
          chmod +x trigger.sh
          ./trigger.sh thenamesumitkumar country-states-pipeline country.yml main "{\"country\":\"${{ github.event.inputs.country }}\"}"
